# Generated by Django 4.1.1 on 2022-11-19 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profilepic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(default='profile_pic/avatar7.png', max_length=255, upload_to=users.models.user_directory_path)),
                ('selected', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profilepic', to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileAPIKey',
            fields=[
                ('apiKey', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='users.profile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='profilepic',
            constraint=models.UniqueConstraint(condition=models.Q(('selected', True)), fields=('profile',), name='one_selected_per_profile'),
        ),
    ]
