# Generated by Django 4.1.1 on 2022-11-16 15:07

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(default='images/no-image.jpg', max_length=255, upload_to=images.models.user_directory_path),
        ),
    ]
