# Generated by Django 4.1.1 on 2022-09-11 13:30

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_category_options_alter_images_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(default='posts/default.jpg', max_length=255, upload_to=images.models.user_directory_path),
        ),
    ]
