# Generated by Django 4.1.1 on 2022-09-15 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_images_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Images'},
        ),
    ]
