# Generated by Django 4.1.1 on 2022-09-26 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_alter_images_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ['id'], 'verbose_name_plural': 'Images'},
        ),
    ]
